services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
    - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml