name: app

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/app.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/app.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: app/pnpm-lock.yaml
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} # ForkからのPRは無視
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run biome
        run: pnpm biome
      - name: Run test
        run: pnpm jest
      - name: Build
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: eas build --platform android --local --non-interactive
